### DISCUSSION TITLE
How to put a date variable in config file?

### DISCUSSION THREAD

**Discussion by eMindFfM** [jblance/mpp-solar#264] [Q&A]
Hi all,
I'm using the MPI 5K and IOBroker to monitor it. So I'm looking for an option to put the date variable into the config in order to get kW per day displayed in the monitoring. So far I tried the following in the mppsolar.conf file:
#command=ED20221006
command=ED%(date +"%Y%m%d")
 
But It does not work. Any hints?
Best Regards

**Comment by jblance** [comment]
there isnt a way at the moment. 
others are using a shell script for this - bit of a cludge, but I need to change the internal workings to make this work properly (its in my todo)

**Comment by Saentist** [comment]
On my inverter command is:
`DAT221208212837`
aka
2022-12-08 21:28:59

**Comment by Saentist** [comment]
Bash script

adapt for your needs
```bash
#bash
getdate=DAT$(date '+%Y%m%d%H%M%S')
echo "$getdate"
echo executing 
echo mpp-solar -p /dev/hidraw2 -o screen -c "$getdate"
mpp-solar -p /dev/hidraw2 -o screen -c "$getdate"
```

**Reply by jblance** [reply]
Sneak preview...
powermon is new (very alpha) command in mpp-solar package
it uses a yaml config file like
```
device:
  name: Test_Inverter
  id: 123456789
  model: 8048MAX
  manufacturer: MPP-Solar
  port:
    baud: 2400
    path: /dev/ttyUSB0
    type: test
    protocol: PI30MAX
  commands:
  - command: QED
    # f_command: f'QED{(date.today()-timedelta(days=1)).strftime("%Y%m%d")}'
    f_command: f'QED{(date.today()).strftime("%Y%m%d")}'
    outputs:
    - name: screen
      tag: Test_Inverter
      filter: ^pv
```
and this yaml supports a formatting command as shown
powermon service also listens to commands and runs them 

still a few key design pieces to sort out so I dont recommend using it yet (yaml format is changing and only supports serial connections atm) however I am using on my install for production monitoring
